### ISSUE TITLE
Python's config merger doesn't handle multi module override

### ISSUE THREAD

**Issue by simonrainerson** [goodbyekansas/nedryglot#34]
Overriding modules for mypy in pyproject.toml can be done with
```toml
[[tool.mypy.overrides]]
module = "some.module.name"
```
But applying the same override to multiple modules is done with
```toml
[[tool.mypy.overrides]]
module = ["some.module.name", "some.other.module.name"]
```

We do not handle the second case.

https://github.com/goodbyekansas/nedryglot/blob/a71f7e6b0da831ca481ff1fb6f853a55e55cf6f6/python/hooks/config-merger.py#L85
